services:
  - type: web
    name: frontend-proyecto-angular
    env: static
    buildCommand: npm install && npm run build:prod
    staticPublishPath: dist/frontend-proyecto-angular/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html