services:
  - type: web
    name: proyecto-angular-completo1
    env: node
    buildCommand: |
      npm install --legacy-peer-deps
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
    healthCheckPath: /
